package dtm.ide.adapter;

import dtm.ide.BuildProblemsCoordinator;
import dtm.ide.JavaEditorRegistry;
import dtm.ide.api.extension.NotificationContext;
import dtm.ide.api.extension.PlatformPopupBuilder;
import dtm.ide.api.extension.Resource;
import dtm.ide.api.extension.editor.EmbeddedCodeEditorSettings;
import dtm.ide.api.extension.output.OutputPanelHandle;
import dtm.ide.api.extension.output.OutputPanelOptions;
import dtm.ide.api.extension.runconfig.RunBreakpointData;
import dtm.ide.api.extension.runconfig.RunConfigurationData;
import dtm.ide.api.extension.runconfig.RunExecutionContext;
import dtm.ide.api.extension.runconfig.RunProcessHandle;
import dtm.ide.api.extension.screen.ToolIconType;
import dtm.ide.api.project.editor.IdeEditorContext;
import dtm.ide.build.BuildResult;
import dtm.ide.build.BuildSystem;
import dtm.ide.build.MavenPluginGoals;
import dtm.ide.coverage.CoverageProvisioner;
import dtm.ide.debug.BuildToolDebugListener;
import dtm.ide.debug.JavaDebugSession;
import dtm.ide.deps.PomProperties;
import dtm.ide.editor.BuildFileCompletionProvider;
import dtm.ide.editor.JavaFastCompletionProvider;
import dtm.ide.index.JavaLexicalIndex;
import dtm.ide.lsp.api.ClassFileSupport;
import dtm.ide.lsp.api.JavaLanguageServer;
import dtm.ide.navigation.JavaNavigation.Kind;
import dtm.ide.project.JavaFileChangeRouter;
import dtm.ide.project.JavaModule;
import dtm.ide.project.JavaProjectDescriptor;
import dtm.ide.run.MainClassScanner;
import dtm.ide.sdk.DownloadProgressListener;
import dtm.ide.sdk.JdkInstallation;
import dtm.ide.sdk.JdkService;
import dtm.ide.settings.JavaPluginSettings;
import dtm.ide.test.JavaTestRunner;
import dtm.ide.ui.JavaBuildToolsPanel;
import dtm.ide.ui.JavaTestExplorerPanel;
import dtm.ide.ui.JavaTodoPanel;
import dtm.request_actions.http.download.core.DownloadObserver;
import dtm.stools.component.panels.dock.DockRegion;
import dtm.stools.component.panels.editor.code.CodeEditor;
import dtm.stools.component.panels.editor.code.api.Location;
import dtm.stools.component.popup.ModernComponentDialog;
import dtm.stools.component.popup.ModernDialog;
import dtm.stools.component.popup.ModernInputDialog;

import java.awt.Dimension;
import java.awt.Point;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import java.util.function.Supplier;
import javax.swing.*;
import javax.swing.Icon;
import javax.swing.JComponent;

public interface AdapterHost extends AdapterContext {
    String registerTodoPanel(JavaTodoPanel panel, Icon icon);
    void requestOpenToolPanel(String panelId);
    void openAt(Path file, int line, int column);
    JdkService jdkService();
    JdkInstallation projectJdk();
    void projectJdk(JdkInstallation jdk);
    void descriptor(JavaProjectDescriptor descriptor);
    long lifecycleTicket();
    long nextLifecycleTicket();
    boolean isCurrent(long ticket, Path root);
    <T> T timed(String label, Supplier<T> operation);
    void rebuildLexicalIndex(JavaProjectDescriptor descriptor);
    void refreshRunButtonsForCurrentFile();
    void reloadBuildToolsPanel();
    void reloadStructurePanel();
    void setStatusBarText(String text);
    DownloadProgressListener progressListener();
    void resolveProjectJdk(long ticket, Path root);
    JavaPluginSettings settings();
    JComponent dependencyLibrariesView();
    void syncProject();
    void requestRefreshCodeLenses(Path file);
    void refreshDiagnosticsOfOpenJavaEditors();
    BuildSystem buildSystem();
    java.util.Optional<String> runtimeClasspathOf(BuildSystem build, JavaModule module);
    String registerBottomPanel(String title, Icon icon, JComponent panel);
    void openWebBrowser(String url);
    MavenPluginGoals pluginGoals();
    void clearPluginRepositoryPath();
    BuildSystem currentBuildSystem();
    List<RunConfigurationData> requestRunConfigurations();
    RunConfigurationData requestSaveRunConfiguration(RunConfigurationData configuration);
    boolean requestRemoveRunConfiguration(String id);
    Set<Path> migratedBuildRunConfigurations();
    void showPopup(PlatformPopupBuilder popup);
    BuildToolDebugListener openBuildDebugListener(JavaModule module, Runnable cancelProcess) throws IOException;
    OutputPanelHandle requestOutputPanel(String title, OutputPanelOptions options);
    void writeOutput(OutputPanelHandle panel, String line);
    void publishBuildDiagnostics(BuildResult result, boolean revealOnFailure);
    JavaBuildToolsPanel buildToolsPanel();
    JavaLanguageServer languageServer();
    void requestShowRunOutput();
    JavaTestRunner newTestRunner(JavaProjectDescriptor current, BuildSystem build);
    void publishTestDiagnostics(BuildResult result);
    void clearCoverage();
    CoverageProvisioner coverageProvisioner();
    void readCoverage(Path execFile, JavaProjectDescriptor current);
    AtomicReference<Runnable> pendingTestDebug();
    JavaTestRunner activeTestRunner();
    JavaModule mostSpecificModule(Collection<JavaModule> modules, Path file);
    BuildToolDebugListener openBuildDebugListener(JavaModule module, Runnable cancelProcess, Runnable onAttach)
            throws IOException;
    void showProgress(String id, String message, boolean cancellable, Runnable onCancel);
    void hideProgress(String id);
    void requestSetRunButtonLoading(boolean loading);
    void requestSetRunButtonRunning(boolean running);
    void warmUpDebugAdapter();
    boolean hasRunningProcess();
    JdkService currentJdkService();
    JavaTestExplorerPanel testPanel();
    Map<Path, IdeEditorContext> javaEditors();
    void requestOpenFile(Path file);
    IdeEditorContext activeJavaEditor();
    void requestCodeEditorAutocomplete();
    SpringSupport spring();
    BuildFileCompletionProvider buildFileCompletion();
    JavaFastCompletionProvider fastCompletion();
    JavaLexicalIndex lexicalIndex();
    boolean isSpringNavigationEnabled();
    BuildProblemsCoordinator problems();
    Resource resource();
    void requestRefreshDiagnostics(Path file);
    void requestShowCodeActions(Path file);
    JavaLanguageServer runningServerFor(Path file);
    void showProgress(String id, String message);
    void updateProgress(String id, String message, int percent, boolean cancellable, Runnable onCancel);
    <T> ModernComponentDialog.ModernComponentDialogBuilder<T> createModernComponentDialogBuilder();
    ModernDialog.ModernDialogBuilder createModernDialogBuilder();
    void showUsagesPopup(List<Location> locations, Path currentFile, String currentText,
                         IdeEditorContext context, Point screen, Kind kind);
    IdeEditorContext editorContextFor(Path file);
    IdeEditorContext getEditor(Path file);
    CoverageSupport coverage();
    String testPanelId();
    void navigateToLocation(Location location, Path path);
    void openSpringExplorer();
    Optional<MainClassScanner.MainClass> currentMainClass();
    RunProcessHandle requestRunConfigurationExecution(String id, boolean debug);
    RunProcessHandle launch(RunConfigurationData configuration, RunExecutionContext context);
    RunProcessHandle launchDebug(RunConfigurationData configuration, RunExecutionContext context);
    JavaModule moduleContaining(JavaProjectDescriptor descriptor, Path file, boolean testRoots);
    void ensureTestPanel();
    List<Location> uniqueLocations(List<Location> locations);
    CodeLensSupport codeLens();
    ClassFileSupport classFileUris();
    AtomicLong navigationTicket();
    JavaEditorRegistry editors();
    IdeEditorContext getEditor(Path file, boolean focus, Consumer<IdeEditorContext> onReady);
    boolean closeCenterTab(String id);
    CodeEditor requestEmbeddedCodeEditor(String name, String source, EmbeddedCodeEditorSettings settings);
    String openCenterTab(String id, String title, JComponent component, boolean closable);
    boolean isDebugPaused();
    DiagnosticsEngine diagnostics();
    IdeEditorContext getEditor(Path file, boolean focus);
    <T> ModernComponentDialog.ModernComponentDialogBuilder<T> createModernComponentDialogBuilder(Class<T> type);
    JavaDebugSession debugSession();
    Object monitor();
    AtomicBoolean debugActiveFlag();
    NavigationViews navigationViews();
    void requestSetHotReloadButtonVisible(boolean visible);
    void requestSetHotReloadButtonEnabled(boolean enabled);
    JavaLanguageServer ensureLanguageServer();
    String registerToolPanel(DockRegion region, String title, ToolIconType icon, JComponent component,
                             Dimension size);
    void closeDebugRelay();
    boolean supportsHotReloadForSelection();
    void requestRepaintCodeEditor(Path file);
    void requestRepaintCodeEditorBreakpointLine(Path file);
    DebugSupport debug();
    AtomicBoolean buildRunning();
    boolean isUnloaded();
    String buildProgressAction(BuildSystem.BuildAction action);
    void updateProgress(String id, String message, int percent);
    List<RunBreakpointData> requestWorkspaceBreakpoints();
    void requestSetRunButtonEnabled(boolean enabled);
    void requestSetDebugButtonEnabled(boolean enabled);
    void requestSetCoverageButtonVisible(boolean visible);
    void requestSetCoverageButtonEnabled(boolean enabled);
    void runBuild(BuildSystem.BuildAction action, String title, JavaModule module);
    void openDependencyManager();
    void clearCaches();
    void requestProjectTreeViewRefresh();
    ModernInputDialog.ModernInputDialogBuilder createModernInputDialogBuilder();
    String readCurrentText(Path file);
    void onBuildFileChanged(Path file);
    JavaFileChangeRouter fileChangeRouter();
    void requestProjectTreeRevealCreated(Path file);
    SourceActionSupport sourceActions();
    AtomicLong navigationRequestTicket();
    PomProperties pomProperties();
    boolean isIndexing(Path file);
    IdeEditorContext liveEditorFor(Path file);
    void classFileUris(ClassFileSupport support);
    void languageServer(JavaLanguageServer server);
    void observeSyncWork(boolean active);
    DownloadObserver resolveDownloadObserver();
    ConditionalBreakpointSupport conditionalBreakpoints();
    CompletionEngine completionEngine();
    void finishDiagnosticReanalysis(long ticket, Path root, boolean successful);
    void refreshProblemsPanel();
    void createNotification(NotificationContext context);
    void requestRefreshInlayHints(Path file);
    void requestRefreshSemanticTokens(Path file);
}
